craete the backend for google calendar
CA-G12/Share-Us pull request #104
Opened 2022-11-09 19:22 UTC by Bakeza

Relates #103

2022-11-10 14:30 UTC, shamskhodary approved these changes

2022-11-10 14:32 UTC, SaifHayek approved these changes

2022-11-11 18:03 UTC, SaifHayek submitted a review, later dismissed

2022-11-13 14:40 UTC, aaamra requested changes

2022-11-13 14:40 UTC, aaamra commented on client/src/App.tsx
> +    // },
remove the comments

2022-11-13 14:40 UTC, aaamra commented on client/src/components/AddEvent/index.tsx
> +            </div> */}
remove the comments

2022-11-13 14:40 UTC, aaamra commented on client/src/components/GoogleCalendar/index.tsx
> +  // const [openOnce, setOpenOnce] = React.useState(true)
remove this comment

2022-11-13 14:40 UTC, aaamra commented on src/controllers/GoogleCalendar.ts
> +const Credentials = async (req:IUserRequest, res:Response):Promise<void> => {
dont forget the validation

2022-11-13 14:40 UTC, aaamra commented on src/helpers/expressWrapper.ts
> +      console.log(err)
remove this

2022-11-13 14:40 UTC, aaamra commented on src/routes/events/index.ts
> +// router.get('/events/googleCalendar/:id', expressWrapper(GetEventId))
remove this comment

2022-11-13 18:28 UTC, shamskhodary submitted a review, later dismissed

2022-11-13 18:32 UTC, SaifHayek approved these changes

2022-11-15 14:20 UTC, MostafaBalousha123 submitted a review, later dismissed

2022-11-15 16:38 UTC, aaamra approved these changes

2022-11-15 16:39 UTC, merged