create event details function and query and test it
CA-G12/Share-Us pull request #41
Opened 2022-10-16 12:13 UTC by MostafaBalousha123

relates #12

2022-10-17 23:49 UTC, Ibrahim-Jarada reviewed
I notice some features of Eslint not working well and I believe its from  configuration.
consider the configuration below.
After that some Eslint errors will popup you will need to fix the reasonable ones and maybe you will need to turn off some weird rules.
```
 "extends": [
        "standard-with-typescript",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/eslint-recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 11,
        "sourceType": "module",
        "project": "./tsconfig.json"
    },
```

2022-10-17 23:49 UTC, Ibrahim-Jarada commented on src/controllers/EventsController.ts
> +    const eventDetails:any = await Event.findOne({
```suggestion
    const eventDetails = await Event.findOne({
```

2022-10-17 23:49 UTC, Ibrahim-Jarada commented on src/controllers/EventsController.ts
> +  public static async index (req: Request, res: Response) {
You may need to specify the return type of the function
```suggestion
  public static async index (req: Request, res: Response):Promise<void> {
```

2022-10-17 23:49 UTC, Ibrahim-Jarada commented on src/controllers/EventsController.ts
> +      latitude: data.latitude
Just my preference
```suggestion
    await querySchema.validateAsync(req.body)
    const {
      name,
      description,
      img,
      status,
      startTime,
      endTime,
      longitude,
      latitude
    } = req.body
    const event = await Event.create({
      name,
      description,
      img,
      status,
      startTime,
      endTime,
      longitude,
      latitude
    })
```

2022-10-18 16:04 UTC, aaamra requested changes

2022-10-18 16:04 UTC, aaamra commented on .eslintrc.json
> +        "max-len": ["error", { "code": 200 }]
i think 100 chars is enough
```suggestion
        "max-len": ["error", { "code": 100 }]
```

2022-10-18 16:04 UTC, aaamra commented on client/.eslintrc.json
> +        "max-len": ["error", { "code": 200 }],
```suggestion
        "max-len": ["error", { "code": 100 }],
```

2022-10-18 16:20 UTC, aaamra approved these changes

2022-10-18 16:41 UTC, shamskhodary approved these changes

2022-10-18 18:03 UTC, Ibrahim-Jarada approved these changes

2022-10-18 18:03 UTC, Ibrahim-Jarada commented on src/controllers/EventsController.ts
>    public static async show (req: Request, res: Response) {
```suggestion
  public static async show (req: Request, res: Response):Promise<void> {
```

2022-10-18 18:03 UTC, Ibrahim-Jarada commented on src/controllers/EventsController.ts
> +  public static async store (req: Request, res: Response) {
```suggestion
  public static async store (req: Request, res: Response):Promise<void> {
```

2022-10-18 18:08 UTC, Bakeza approved these changes

2022-10-18 19:56 UTC, SaifHayek approved these changes

2022-10-19 02:07 UTC, merged