51 search result component
CA-G12/Share-Us pull request #59
Opened 2022-10-23 13:27 UTC by Bakeza

2022-10-27 08:51 UTC, aaamra requested changes

2022-10-27 08:51 UTC, aaamra commented on client/src/components/Navbar/Navbar.tsx
> +  }
just a suggestions
```suggestion
  const [category, setCategory] = useState<string>('event')
  const [search, setSearch] = useState<string>('')
  // eslint-disable-next-line no-unused-vars
  const [_, setSearchParams] = useSearchParams()

  const handleSearch = ():void => {
    if (location.pathname !== '/search') {
      navigate({
        pathname: '/search',
        search: `${createSearchParams({ category, q: search })}`,
      })
    } else {
      setSearchParams({
        category,
        q: search,
      })
    }
  }
```

2022-10-27 08:51 UTC, aaamra commented on client/src/components/SearchResult/index.tsx
> +        </Card>
i think you can extract this to a separate component

2022-10-27 08:51 UTC, aaamra commented on client/src/components/SearchResult/index.tsx
> +        </Card>
and this one

2022-10-27 08:51 UTC, aaamra commented on client/src/components/SearchResult/index.tsx
> +        </Card>
and this one

2022-10-27 08:51 UTC, aaamra commented on client/src/services/ApiService.ts
> +    // this.axios.defaults.baseURL = 'http://localhost:8080'
remove this comment

2022-10-28 19:10 UTC, aaamra requested changes

2022-10-28 19:10 UTC, aaamra commented on client/src/components/SearchResult/EventCardHandler.tsx
> +              ? 'red' : 'transparent'}
i think you can extract this logic to a function to make it more readable

something like that
```js
const getStatusClassName = (status) => {
  if(status === 'in-progress'){
     return 'green'
  } else if () {
    /// etc
  } else {
     //etc
  }
}
```

2022-10-28 19:10 UTC, aaamra commented on client/src/components/SearchResult/FriendCardHandler.tsx
> +/* eslint-disable react/require-default-props */
don't disable eslint

2022-10-28 19:10 UTC, aaamra commented on client/src/components/SearchResult/FriendCardHandler.tsx
> +}
the same interface issue here

2022-10-28 19:10 UTC, aaamra commented on client/src/components/SearchResult/FriendCardHandler.tsx
> +const FriendCardHandler:FC<cardData> = ({
also the same for component name

2022-10-28 19:10 UTC, aaamra commented on client/src/interfaces/ISearchResult.tsx
> +}
I think we don't use this interface
so you can delete it

2022-10-29 17:02 UTC, aaamra approved these changes

2022-10-29 17:03 UTC, SaifHayek approved these changes

2022-10-29 17:04 UTC, MostafaBalousha123 approved these changes

2022-10-29 17:04 UTC, merged