create calendar page
CA-G12/Share-Us pull request #63
Opened 2022-10-26 08:43 UTC by SaifHayek

2022-10-27 21:46 UTC, aaamra requested changes

2022-10-27 21:46 UTC, aaamra commented on client/src/components/EventCalendar/index.tsx
> +  }
don't use `window.confirm` you can use a component from MUI
or you can use SweetAlert

or you don't have to confirm the user when he clicks on the event (and that's my opinion)

2022-10-27 21:46 UTC, aaamra commented on test/eventJoinedPeople.test.ts
> +const token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtb3N0YWZhIiwiaWF0IjoxNjY2NTExODQwfQ.LUdcIEgpLB_4m9p8tnQGVKwihZyqlEob_7HsQSXZUgc'
i thinks this token exists in our config
```suggestion
const token = config.token
```

2022-10-27 21:46 UTC, aaamra commented on src/controllers/EventParticipantsController.ts
> +    console.log('yyyyy')
```suggestion
```

2022-10-27 21:46 UTC, aaamra commented on client/src/components/EventCalendar/index.tsx
> +  const [initialEvents, setInitialEvents] = useState([])
```suggestion
  const [joindEvents, setJoindEvents] = useState([])
```

2022-10-27 21:46 UTC, aaamra commented on client/src/components/EventCalendar/index.tsx
> +  const renderEventContent = (eventInfo:any):any => {
remove `any`

2022-10-27 21:46 UTC, aaamra commented on client/src/components/EventCalendar/index.tsx
> +  const renderSidebarEvent = (event:any):any => (
remove `any`
and you can move this to other file and make it as a react component with `props`

2022-10-28 19:21 UTC, aaamra approved these changes

2022-10-28 19:23 UTC, shamskhodary approved these changes

2022-10-28 19:26 UTC, MostafaBalousha123 approved these changes

2022-10-28 20:14 UTC, Bakeza approved these changes

2022-10-28 20:14 UTC, merged