[react, mui, css] create login and signUp components and style it
CA-G12/Share-Us pull request #8
Opened 2022-10-11 11:46 UTC by MostafaBalousha123

![Screenshot (27)](https://user-images.githubusercontent.com/95299650/195081374-4e50f9ec-3fcf-40d9-8273-8862087518a1.png)

2022-10-11 12:38 UTC, aaamra reviewed
![image](https://user-images.githubusercontent.com/78448519/195092705-fc27b588-a8ed-4261-a3ff-64b40def487e.png)

i think the `auth` folder should be in the `pages` folder.
not in `components`

2022-10-11 12:38 UTC, aaamra commented on client/public/index.html
> +    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
it's not good to use cdn links for icons and styles with react
you can just install it in your app with `npm i ....`
and Marital UI has a great collection of icons
[MUI Icons](https://mui.com/material-ui/material-icons/)

2022-10-11 12:40 UTC, aaamra reviewed
![image](https://user-images.githubusercontent.com/78448519/195092965-682e6737-d62a-41a6-be0a-9b6066686ddb.png)

you are using MUI but you did not installed it !?
how it works for you ?

2022-10-11 12:43 UTC, aaamra commented on client/src/components/auth/Login.tsx
> +    <img src="https://cdn.discordapp.com/attachments/959502807071867000/1029343065720246354/pexels-rodnae-productions-7348675.jpg" alt="test" style={{ margin: '0', padding: '0' }} />
don't use links for your images
you can add it in the `assets` folder

2022-10-11 12:43 UTC, aaamra commented on client/src/components/auth/SignUp.tsx
> +    <img src="https://cdn.discordapp.com/attachments/959502807071867000/1029343065720246354/pexels-rodnae-productions-7348675.jpg" alt="test" />
same issue here
put the image in the `assets` folder

2022-10-11 12:45 UTC, aaamra commented on client/src/components/auth/auth.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
i think if you add this font in a global css file may be better to keep the website with the same font

2022-10-12 07:52 UTC, Bakeza submitted a review, later dismissed

2022-10-12 07:55 UTC, shamskhodary approved these changes

2022-10-13 18:55 UTC, aaamra requested changes
add this rule in `.eslintrc.json`
```
"max-len": ["error", { "code": 80 }]
```

2022-10-13 18:55 UTC, aaamra commented on client/package.json
> +    "npm": "^8.19.2",
why did you installed this ?

2022-10-13 18:55 UTC, aaamra commented on client/package.json
> +    "styled-components": "^5.3.6",
and this

2022-10-14 21:33 UTC, MostafaBalousha123 commented on client/package.json
> +    "npm": "^8.19.2",
Oh technical error 😢

2022-10-14 21:34 UTC, MostafaBalousha123 commented on client/package.json
> +    "styled-components": "^5.3.6",
this for MUI

2022-10-15 19:41 UTC, aaamra approved these changes

2022-10-15 19:52 UTC, shamskhodary approved these changes

2022-10-16 07:47 UTC, Bakeza submitted a review, later dismissed

2022-10-16 07:51 UTC, Bakeza approved these changes

2022-10-16 07:52 UTC, shamskhodary approved these changes

2022-10-16 08:07 UTC, aaamra approved these changes

2022-10-16 08:10 UTC, merged