preparing for deploying
CA-G12/Share-Us pull request #94
Opened 2022-11-04 18:19 UTC by shamskhodary

2022-11-06 14:00 UTC, aaamra requested changes

2022-11-06 14:00 UTC, aaamra commented on src/db/connection.ts
> +        })
this logic should be in `environment.ts` file

2022-11-06 14:36 UTC, aaamra approved these changes

2022-11-07 11:34 UTC, SaifHayek approved these changes

2022-11-07 12:35 UTC, MostafaBalousha123 approved these changes

2022-11-07 12:36 UTC, merged