cerate chat system
CA-G12/Share-Us pull request #96
Opened 2022-11-04 20:41 UTC by SaifHayek

related #95

2022-11-07 10:08 UTC, aaamra requested changes

2022-11-07 10:08 UTC, aaamra commented on src/controllers/UserProfileController.ts
> +  }
you can simplify it like this

```suggestion
    const users = await User.findAll({
      where: {
        [Op.or]: [
          { '$received.senderId$': id },
          { '$sent.receiverId$': id }
        ]
      },
      attributes: ['id', 'username', 'profileImg', 'blocked'],
      include: [{
        model: Chat,
        as: 'received',
        attributes: []
      }, {
        model: Chat,
        as: 'sent',
        attributes: []
      }]
    })

    res.json({
      data: users, message: Message.SUCCESS
    })
  }
```

2022-11-07 13:53 UTC, shamskhodary submitted a review, later dismissed

2022-11-08 09:48 UTC, aaamra approved these changes

2022-11-08 09:49 UTC, MostafaBalousha123 approved these changes

2022-11-08 09:50 UTC, shamskhodary approved these changes

2022-11-08 09:50 UTC, merged